name: lightgaussian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=0.8.1
  - python=3.9
  - pip=22.3.1
  - pytorch=2.0.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - icecream
  - mkl==2024.0
  - pip:
    - submodules/compress-diff-gaussian-rasterization
    - submodules/simple-knn
